import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Image from "next/image";

import { api } from "../utils/api";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import PostOfficeSelector from "../components/PostOfficeSelector";
import NoticeToCompleteProfile from "../components/NoticeToCompleteProfile";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Worker's Loogbook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <NoticeToCompleteProfile />
      <header className="relative">
        <div className="absolute left-0 right-0 top-0 bottom-0 -z-10">
          <Image
            className="h-full w-full object-cover brightness-75 filter"
            width={1920}
            height={1080}
            alt="Home Banner"
            src="/images/home-banner.webp"
          />
        </div>
        <div className="flex flex-col items-center justify-center gap-8 py-48">
          <h1 className="text-5xl text-white">
            Get Your Service Without Hassle
          </h1>
          <div className="flex gap-7">
            <PostOfficeSelector />
            <div className="w-96">
              <div className="relative mt-1 flex items-center">
                <input
                  type="text"
                  name="search"
                  id="search"
                  placeholder="Search for a service"
                  className="block w-full rounded-md border-gray-300 pr-12 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                />
                <div className="absolute inset-y-0 right-0 flex py-1.5 pr-1.5">
                  <kbd className="inline-flex items-center rounded border border-gray-200 px-2 font-sans text-sm font-medium text-gray-400">
                    ⌘K
                  </kbd>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
      {/* <Link className="text-white" href="/site-admin">
        Admin Panel
      </Link> */}
      <main>
        <div className="container mx-auto px-4 py-8">
          <h1 className="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl">
            Services
          </h1>
          <hr className="mt-2 mb-10 border-2 border-dashed border-black opacity-50" />
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
            <div className="rounded-md bg-white p-4 shadow-md">
              <h2 className="text-2xl font-semibold">Post Office</h2>
              <p className="text-gray-500">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis
                quod, voluptate, quia, voluptas quas voluptatem quibusdam
                voluptatum quae quidem natus quos. Quisquam, quae. Quisquam
                voluptas quae, quod quibusdam quia.
              </p>
            </div>
          </div>
        </div>
      </main>
      <div className="mt-auto">
        <Footer />
      </div>
    </>
  );
};

export default Home;
