import { PostOfficeInfo } from "./IPostOfficeInfo";

const postOffices2: PostOfficeInfo = {
  query: {
    codes: [
      "8132",
      "8133",
      "8140",
      "8141",
      "8142",
      "2300",
      "2301",
      "2302",
      "2303",
      "2310",
      "2316",
      "2320",
      "2326",
      "2330",
      "2331",
      "2336",
      "2337",
      "2338",
      "2340",
      "2341",
      "2350",
      "2360",
      "2370",
      "2371",
      "2380",
      "2390",
      "7900",
      "7901",
      "7902",
      "7903",
      "7904",
      "7910",
      "7911",
      "7920",
      "7921",
      "7930",
      "7931",
      "7932",
      "7933",
      "1800",
      "1801",
      "1802",
      "1803",
      "1804",
      "1810",
      "1811",
      "1820",
      "1821",
      "1822",
      "1830",
      "1831",
      "1840",
      "1850",
      "1851",
      "1852",
      "1853",
      "1860",
      "1333",
      "1334",
      "1335",
      "1500",
      "1501",
      "1502",
      "1503",
      "1510",
      "1511",
      "1512",
      "1520",
      "1521",
      "1522",
      "1523",
      "1524",
      "1525",
      "1526",
      "1527",
      "1530",
      "1531",
      "1532",
      "1533",
      "1534",
      "1535",
      "1540",
      "1541",
      "1542",
      "1543",
      "1544",
      "1550",
      "1551",
      "1552",
      "1553",
      "1554",
      "1555",
      "1556",
      "1557",
      "1558",
      "1400",
      "1410",
      "1411",
      "1412",
      "1413",
    ],
    country: "bd",
  },
  results: {
    "1333": [
      {
        postal_code: "1333",
        country_code: "BD",
        latitude: "23.46080000",
        longitude: "90.38350000",
        city: "Haridia",
        state: "Dhaka Division",
        city_en: "Haridia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1334": [
      {
        postal_code: "1334",
        country_code: "BD",
        latitude: "23.54120000",
        longitude: "90.25380000",
        city: "Gouragonj",
        state: "Dhaka Division",
        city_en: "Gouragonj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1335": [
      {
        postal_code: "1335",
        country_code: "BD",
        latitude: "23.54120000",
        longitude: "90.25380000",
        city: "Madini Mandal",
        state: "Dhaka Division",
        city_en: "Madini Mandal",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1400": [
      {
        postal_code: "1400",
        country_code: "BD",
        latitude: "23.71970000",
        longitude: "90.56340000",
        city: "Narayanganj Sadar",
        state: "Dhaka Division",
        city_en: "Narayanganj Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1410": [
      {
        postal_code: "1410",
        country_code: "BD",
        latitude: "23.61730000",
        longitude: "90.52830000",
        city: "Bandar",
        state: "Dhaka Division",
        city_en: "Bandar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1411": [
      {
        postal_code: "1411",
        country_code: "BD",
        latitude: "23.61060000",
        longitude: "90.52340000",
        city: "D.C Mills",
        state: "Dhaka Division",
        city_en: "D.C Mills",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1412": [
      {
        postal_code: "1412",
        country_code: "BD",
        latitude: "23.62860000",
        longitude: "90.51970000",
        city: "Nabiganj",
        state: "Dhaka Division",
        city_en: "Nabiganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1413": [
      {
        postal_code: "1413",
        country_code: "BD",
        latitude: "23.61060000",
        longitude: "90.52340000",
        city: "BIDS",
        state: "Dhaka Division",
        city_en: "BIDS",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1500": [
      {
        postal_code: "1500",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "90.41670000",
        city: "Munshiganj Sadar",
        state: "Dhaka Division",
        city_en: "Munshiganj Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1501": [
      {
        postal_code: "1501",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "90.41670000",
        city: "Rikabibazar",
        state: "Dhaka Division",
        city_en: "Rikabibazar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1502": [
      {
        postal_code: "1502",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "90.41670000",
        city: "Mirkadim",
        state: "Dhaka Division",
        city_en: "Mirkadim",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1503": [
      {
        postal_code: "1503",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "90.41670000",
        city: "Kathakhali",
        state: "Dhaka Division",
        city_en: "Kathakhali",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1510": [
      {
        postal_code: "1510",
        country_code: "BD",
        latitude: "23.81670000",
        longitude: "90.48330000",
        city: "Gajaria",
        state: "Dhaka Division",
        city_en: "Gajaria",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1511": [
      {
        postal_code: "1511",
        country_code: "BD",
        latitude: "23.67500000",
        longitude: "90.54620000",
        city: "Hossendi",
        state: "Dhaka Division",
        city_en: "Hossendi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1512": [
      {
        postal_code: "1512",
        country_code: "BD",
        latitude: "23.53330000",
        longitude: "90.60900000",
        city: "Rasulpur",
        state: "Dhaka Division",
        city_en: "Rasulpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1520": [
      {
        postal_code: "1520",
        country_code: "BD",
        latitude: "23.51260000",
        longitude: "90.46640000",
        city: "Tangibari",
        state: "Dhaka Division",
        city_en: "Tangibari",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1521": [
      {
        postal_code: "1521",
        country_code: "BD",
        latitude: "23.45760000",
        longitude: "90.46770000",
        city: "Betkahat",
        state: "Dhaka Division",
        city_en: "Betkahat",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1522": [
      {
        postal_code: "1522",
        country_code: "BD",
        latitude: "23.45760000",
        longitude: "90.46770000",
        city: "Baligao",
        state: "Dhaka Division",
        city_en: "Baligao",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1523": [
      {
        postal_code: "1523",
        country_code: "BD",
        latitude: "23.45760000",
        longitude: "90.46770000",
        city: "Bajrajugini",
        state: "Dhaka Division",
        city_en: "Bajrajugini",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1524": [
      {
        postal_code: "1524",
        country_code: "BD",
        latitude: "23.43540000",
        longitude: "90.45200000",
        city: "Hasail",
        state: "Dhaka Division",
        city_en: "Hasail",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1525": [
      {
        postal_code: "1525",
        country_code: "BD",
        latitude: "23.42490000",
        longitude: "90.48480000",
        city: "Dighirpar",
        state: "Dhaka Division",
        city_en: "Dighirpar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1526": [
      {
        postal_code: "1526",
        country_code: "BD",
        latitude: "23.45760000",
        longitude: "90.46770000",
        city: "Pura EDSO",
        state: "Dhaka Division",
        city_en: "Pura EDSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1527": [
      {
        postal_code: "1527",
        country_code: "BD",
        latitude: "23.45760000",
        longitude: "90.46770000",
        city: "Pura",
        state: "Dhaka Division",
        city_en: "Pura",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1530": [
      {
        postal_code: "1530",
        country_code: "BD",
        latitude: "23.45000000",
        longitude: "90.35000000",
        city: "Lohajang",
        state: "Dhaka Division",
        city_en: "Lohajang",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1531": [
      {
        postal_code: "1531",
        country_code: "BD",
        latitude: "23.45000000",
        longitude: "90.30000000",
        city: "Korhati",
        state: "Dhaka Division",
        city_en: "Korhati",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1532": [
      {
        postal_code: "1532",
        country_code: "BD",
        latitude: "23.45000000",
        longitude: "90.32500000",
        city: "Haldia SO",
        state: "Dhaka Division",
        city_en: "Haldia SO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1533": [
      {
        postal_code: "1533",
        country_code: "BD",
        latitude: "23.45000000",
        longitude: "90.32500000",
        city: "Haridia DESO",
        state: "Dhaka Division",
        city_en: "Haridia DESO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1534": [
      {
        postal_code: "1534",
        country_code: "BD",
        latitude: "23.45000000",
        longitude: "90.32500000",
        city: "Gouragonj",
        state: "Dhaka Division",
        city_en: "Gouragonj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1535": [
      {
        postal_code: "1535",
        country_code: "BD",
        latitude: "23.45000000",
        longitude: "90.32500000",
        city: "Medini Mandal EDSO",
        state: "Dhaka Division",
        city_en: "Medini Mandal EDSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1540": [
      {
        postal_code: "1540",
        country_code: "BD",
        latitude: "23.56040000",
        longitude: "90.34440000",
        city: "Sirajdikhan",
        state: "Dhaka Division",
        city_en: "Sirajdikhan",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1541": [
      {
        postal_code: "1541",
        country_code: "BD",
        latitude: "23.56040000",
        longitude: "90.34440000",
        city: "Kola",
        state: "Dhaka Division",
        city_en: "Kola",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1542": [
      {
        postal_code: "1542",
        country_code: "BD",
        latitude: "23.56040000",
        longitude: "90.34440000",
        city: "Ichapur",
        state: "Dhaka Division",
        city_en: "Ichapur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1543": [
      {
        postal_code: "1543",
        country_code: "BD",
        latitude: "23.56040000",
        longitude: "90.34440000",
        city: "Malkha Nagar",
        state: "Dhaka Division",
        city_en: "Malkha Nagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1544": [
      {
        postal_code: "1544",
        country_code: "BD",
        latitude: "23.56040000",
        longitude: "90.34440000",
        city: "Shekher Nagar",
        state: "Dhaka Division",
        city_en: "Shekher Nagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1550": [
      {
        postal_code: "1550",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "90.65000000",
        city: "Srinagar",
        state: "Dhaka Division",
        city_en: "Srinagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1551": [
      {
        postal_code: "1551",
        country_code: "BD",
        latitude: "23.52840000",
        longitude: "90.36630000",
        city: "Barikhal",
        state: "Dhaka Division",
        city_en: "Barikhal",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1552": [
      {
        postal_code: "1552",
        country_code: "BD",
        latitude: "23.52840000",
        longitude: "90.36630000",
        city: "Mazpara",
        state: "Dhaka Division",
        city_en: "Mazpara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1553": [
      {
        postal_code: "1553",
        country_code: "BD",
        latitude: "23.52840000",
        longitude: "90.36630000",
        city: "Hashara",
        state: "Dhaka Division",
        city_en: "Hashara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1554": [
      {
        postal_code: "1554",
        country_code: "BD",
        latitude: "23.49880000",
        longitude: "90.25710000",
        city: "Kolapara",
        state: "Dhaka Division",
        city_en: "Kolapara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1555": [
      {
        postal_code: "1555",
        country_code: "BD",
        latitude: "23.52840000",
        longitude: "90.36630000",
        city: "Kumarbhog",
        state: "Dhaka Division",
        city_en: "Kumarbhog",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1556": [
      {
        postal_code: "1556",
        country_code: "BD",
        latitude: "23.52840000",
        longitude: "90.36630000",
        city: "Vaggyakul SO",
        state: "Dhaka Division",
        city_en: "Vaggyakul SO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1557": [
      {
        postal_code: "1557",
        country_code: "BD",
        latitude: "23.53640000",
        longitude: "90.19190000",
        city: "Baghra",
        state: "Dhaka Division",
        city_en: "Baghra",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1558": [
      {
        postal_code: "1558",
        country_code: "BD",
        latitude: "23.52840000",
        longitude: "90.36630000",
        city: "Bhaggyakul",
        state: "Dhaka Division",
        city_en: "Bhaggyakul",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Munshiganj",
        province_code: "3059",
      },
    ],
    "1800": [
      {
        postal_code: "1800",
        country_code: "BD",
        latitude: "23.84730000",
        longitude: "89.87070000",
        city: "Manikganj Sadar",
        state: "Dhaka Division",
        city_en: "Manikganj Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1801": [
      {
        postal_code: "1801",
        country_code: "BD",
        latitude: "23.84730000",
        longitude: "89.87070000",
        city: "Manikganj Bazar",
        state: "Dhaka Division",
        city_en: "Manikganj Bazar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1802": [
      {
        postal_code: "1802",
        country_code: "BD",
        latitude: "23.84730000",
        longitude: "89.87070000",
        city: "Gorpara",
        state: "Dhaka Division",
        city_en: "Gorpara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1803": [
      {
        postal_code: "1803",
        country_code: "BD",
        latitude: "23.84990000",
        longitude: "89.87830000",
        city: "Mahadebpur",
        state: "Dhaka Division",
        city_en: "Mahadebpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1804": [
      {
        postal_code: "1804",
        country_code: "BD",
        latitude: "23.84470000",
        longitude: "89.86310000",
        city: "Barangail",
        state: "Dhaka Division",
        city_en: "Barangail",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1810": [
      {
        postal_code: "1810",
        country_code: "BD",
        latitude: "23.88630000",
        longitude: "89.77190000",
        city: "Saturia",
        state: "Dhaka Division",
        city_en: "Saturia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1811": [
      {
        postal_code: "1811",
        country_code: "BD",
        latitude: "23.99390000",
        longitude: "90.04040000",
        city: "Baliati",
        state: "Dhaka Division",
        city_en: "Baliati",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1820": [
      {
        postal_code: "1820",
        country_code: "BD",
        latitude: "23.81290000",
        longitude: "90.14280000",
        city: "Singair",
        state: "Dhaka Division",
        city_en: "Singair",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1821": [
      {
        postal_code: "1821",
        country_code: "BD",
        latitude: "23.82060000",
        longitude: "90.07270000",
        city: "Baira",
        state: "Dhaka Division",
        city_en: "Baira",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1822": [
      {
        postal_code: "1822",
        country_code: "BD",
        latitude: "23.81670000",
        longitude: "90.10780000",
        city: "joymantop",
        state: "Dhaka Division",
        city_en: "joymantop",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1830": [
      {
        postal_code: "1830",
        country_code: "BD",
        latitude: "23.86090000",
        longitude: "89.93660000",
        city: "Lechhraganj",
        state: "Dhaka Division",
        city_en: "Lechhraganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1831": [
      {
        postal_code: "1831",
        country_code: "BD",
        latitude: "23.86090000",
        longitude: "89.93660000",
        city: "Jhitka",
        state: "Dhaka Division",
        city_en: "Jhitka",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1840": [
      {
        postal_code: "1840",
        country_code: "BD",
        latitude: "23.86090000",
        longitude: "89.93660000",
        city: "Gheor",
        state: "Dhaka Division",
        city_en: "Gheor",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1850": [
      {
        postal_code: "1850",
        country_code: "BD",
        latitude: "23.81780000",
        longitude: "89.78660000",
        city: "Shibaloy",
        state: "Dhaka Division",
        city_en: "Shibaloy",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1851": [
      {
        postal_code: "1851",
        country_code: "BD",
        latitude: "23.81780000",
        longitude: "89.78660000",
        city: "Aricha",
        state: "Dhaka Division",
        city_en: "Aricha",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1852": [
      {
        postal_code: "1852",
        country_code: "BD",
        latitude: "23.81780000",
        longitude: "89.78660000",
        city: "Tewta",
        state: "Dhaka Division",
        city_en: "Tewta",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1853": [
      {
        postal_code: "1853",
        country_code: "BD",
        latitude: "23.81780000",
        longitude: "89.78660000",
        city: "Uthli",
        state: "Dhaka Division",
        city_en: "Uthli",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "1860": [
      {
        postal_code: "1860",
        country_code: "BD",
        latitude: "23.86090000",
        longitude: "89.93660000",
        city: "Doulatpur",
        state: "Dhaka Division",
        city_en: "Doulatpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Manikganj",
        province_code: "3056",
      },
    ],
    "2300": [
      {
        postal_code: "2300",
        country_code: "BD",
        latitude: "24.33940000",
        longitude: "90.76030000",
        city: "Kishoreganj Sadar",
        state: "Dhaka Division",
        city_en: "Kishoreganj Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2301": [
      {
        postal_code: "2301",
        country_code: "BD",
        latitude: "24.33940000",
        longitude: "90.76030000",
        city: "Kishoreganj S.Mills",
        state: "Dhaka Division",
        city_en: "Kishoreganj S.Mills",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2302": [
      {
        postal_code: "2302",
        country_code: "BD",
        latitude: "24.33940000",
        longitude: "90.76030000",
        city: "Maizhati",
        state: "Dhaka Division",
        city_en: "Maizhati",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2303": [
      {
        postal_code: "2303",
        country_code: "BD",
        latitude: "24.33940000",
        longitude: "90.76030000",
        city: "Nilganj",
        state: "Dhaka Division",
        city_en: "Nilganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2310": [
      {
        postal_code: "2310",
        country_code: "BD",
        latitude: "24.46780000",
        longitude: "90.87050000",
        city: "Karimganj",
        state: "Dhaka Division",
        city_en: "Karimganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2316": [
      {
        postal_code: "2316",
        country_code: "BD",
        latitude: "24.46780000",
        longitude: "90.87050000",
        city: "Tarial",
        state: "Dhaka Division",
        city_en: "Tarial",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2320": [
      {
        postal_code: "2320",
        country_code: "BD",
        latitude: "24.34910000",
        longitude: "90.95710000",
        city: "Hossenpur",
        state: "Dhaka Division",
        city_en: "Hossenpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2326": [
      {
        postal_code: "2326",
        country_code: "BD",
        latitude: "24.34910000",
        longitude: "90.95710000",
        city: "Pakundia",
        state: "Dhaka Division",
        city_en: "Pakundia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2330": [
      {
        postal_code: "2330",
        country_code: "BD",
        latitude: "24.21620000",
        longitude: "90.95000000",
        city: "Katiadi",
        state: "Dhaka Division",
        city_en: "Katiadi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2331": [
      {
        postal_code: "2331",
        country_code: "BD",
        latitude: "24.21620000",
        longitude: "90.95000000",
        city: "Gochhihata",
        state: "Dhaka Division",
        city_en: "Gochhihata",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2336": [
      {
        postal_code: "2336",
        country_code: "BD",
        latitude: "24.21620000",
        longitude: "90.95000000",
        city: "Bajitpur",
        state: "Dhaka Division",
        city_en: "Bajitpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2337": [
      {
        postal_code: "2337",
        country_code: "BD",
        latitude: "24.21620000",
        longitude: "90.95000000",
        city: "Sararchar",
        state: "Dhaka Division",
        city_en: "Sararchar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2338": [
      {
        postal_code: "2338",
        country_code: "BD",
        latitude: "24.21620000",
        longitude: "90.95000000",
        city: "Laksmipur",
        state: "Dhaka Division",
        city_en: "Laksmipur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2340": [
      {
        postal_code: "2340",
        country_code: "BD",
        latitude: "24.15500000",
        longitude: "90.90000000",
        city: "Kuliarchar",
        state: "Dhaka Division",
        city_en: "Kuliarchar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2341": [
      {
        postal_code: "2341",
        country_code: "BD",
        latitude: "24.15500000",
        longitude: "90.90000000",
        city: "Chhoysuti",
        state: "Dhaka Division",
        city_en: "Chhoysuti",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2350": [
      {
        postal_code: "2350",
        country_code: "BD",
        latitude: "24.34910000",
        longitude: "90.95710000",
        city: "Bhairab",
        state: "Dhaka Division",
        city_en: "Bhairab",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2360": [
      {
        postal_code: "2360",
        country_code: "BD",
        latitude: "24.34910000",
        longitude: "90.95710000",
        city: "Nikli",
        state: "Dhaka Division",
        city_en: "Nikli",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2370": [
      {
        postal_code: "2370",
        country_code: "BD",
        latitude: "24.38950000",
        longitude: "91.16570000",
        city: "MIthamoin",
        state: "Dhaka Division",
        city_en: "MIthamoin",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2371": [
      {
        postal_code: "2371",
        country_code: "BD",
        latitude: "24.38950000",
        longitude: "91.16570000",
        city: "Abdullahpur",
        state: "Dhaka Division",
        city_en: "Abdullahpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2380": [
      {
        postal_code: "2380",
        country_code: "BD",
        latitude: "24.34910000",
        longitude: "90.95710000",
        city: "Ostagram",
        state: "Dhaka Division",
        city_en: "Ostagram",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "2390": [
      {
        postal_code: "2390",
        country_code: "BD",
        latitude: "24.52690000",
        longitude: "91.09600000",
        city: "Itna",
        state: "Dhaka Division",
        city_en: "Itna",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Kishoreganj",
        province_code: "3048",
      },
    ],
    "7900": [
      {
        postal_code: "7900",
        country_code: "BD",
        latitude: "23.16910000",
        longitude: "90.22580000",
        city: "Madaripur Sadar",
        state: "Dhaka Division",
        city_en: "Madaripur Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7901": [
      {
        postal_code: "7901",
        country_code: "BD",
        latitude: "23.16910000",
        longitude: "90.22580000",
        city: "Charmugria",
        state: "Dhaka Division",
        city_en: "Charmugria",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7902": [
      {
        postal_code: "7902",
        country_code: "BD",
        latitude: "23.16910000",
        longitude: "90.22580000",
        city: "Kulpaddi",
        state: "Dhaka Division",
        city_en: "Kulpaddi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7903": [
      {
        postal_code: "7903",
        country_code: "BD",
        latitude: "23.16910000",
        longitude: "90.22580000",
        city: "Habiganj",
        state: "Dhaka Division",
        city_en: "Habiganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7904": [
      {
        postal_code: "7904",
        country_code: "BD",
        latitude: "23.16910000",
        longitude: "90.22580000",
        city: "Mustafapur",
        state: "Dhaka Division",
        city_en: "Mustafapur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7910": [
      {
        postal_code: "7910",
        country_code: "BD",
        latitude: "23.20690000",
        longitude: "90.05050000",
        city: "Rajoir",
        state: "Dhaka Division",
        city_en: "Rajoir",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7911": [
      {
        postal_code: "7911",
        country_code: "BD",
        latitude: "23.22210000",
        longitude: "90.00130000",
        city: "Khalia",
        state: "Dhaka Division",
        city_en: "Khalia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7920": [
      {
        postal_code: "7920",
        country_code: "BD",
        latitude: "23.10000000",
        longitude: "90.26670000",
        city: "Kalkini",
        state: "Dhaka Division",
        city_en: "Kalkini",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7921": [
      {
        postal_code: "7921",
        country_code: "BD",
        latitude: "23.10000000",
        longitude: "90.26670000",
        city: "Sahabrampur",
        state: "Dhaka Division",
        city_en: "Sahabrampur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7930": [
      {
        postal_code: "7930",
        country_code: "BD",
        latitude: "23.27860000",
        longitude: "90.17410000",
        city: "Barhamganj",
        state: "Dhaka Division",
        city_en: "Barhamganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7931": [
      {
        postal_code: "7931",
        country_code: "BD",
        latitude: "23.27860000",
        longitude: "90.17410000",
        city: "Nilaksmibandar",
        state: "Dhaka Division",
        city_en: "Nilaksmibandar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7932": [
      {
        postal_code: "7932",
        country_code: "BD",
        latitude: "23.23650000",
        longitude: "90.14240000",
        city: "Bahadurpur",
        state: "Dhaka Division",
        city_en: "Bahadurpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "7933": [
      {
        postal_code: "7933",
        country_code: "BD",
        latitude: "23.32080000",
        longitude: "90.20570000",
        city: "Umedpur",
        state: "Dhaka Division",
        city_en: "Umedpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Madaripur",
        province_code: "3054",
      },
    ],
    "8132": [
      {
        postal_code: "8132",
        country_code: "BD",
        latitude: "23.23570000",
        longitude: "89.72050000",
        city: "Ratoil",
        state: "Dhaka Division",
        city_en: "Ratoil",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8133": [
      {
        postal_code: "8133",
        country_code: "BD",
        latitude: "23.23570000",
        longitude: "89.72050000",
        city: "Jonapur",
        state: "Dhaka Division",
        city_en: "Jonapur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8140": [
      {
        postal_code: "8140",
        country_code: "BD",
        latitude: "23.55060000",
        longitude: "90.16230000",
        city: "Maksudpur",
        state: "Dhaka Division",
        city_en: "Maksudpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8141": [
      {
        postal_code: "8141",
        country_code: "BD",
        latitude: "23.40860000",
        longitude: "90.01450000",
        city: "Batkiamari",
        state: "Dhaka Division",
        city_en: "Batkiamari",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8142": [
      {
        postal_code: "8142",
        country_code: "BD",
        latitude: "23.26670000",
        longitude: "89.86670000",
        city: "Khandarpara",
        state: "Dhaka Division",
        city_en: "Khandarpara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
  },
};

export default postOffices2;
