import { PostOfficeInfo } from "./IPostOfficeInfo";
const postOffices1: PostOfficeInfo = {
  query: {
    codes: [
      "1000",
      "1100",
      "1203",
      "1204",
      "1205",
      "1206",
      "1207",
      "1208",
      "1209",
      "1211",
      "1212",
      "1213",
      "1214",
      "1215",
      "1216",
      "1217",
      "1219",
      "1222",
      "1223",
      "1225",
      "1229",
      "1230",
      "1232",
      "1310",
      "1311",
      "1312",
      "1313",
      "1320",
      "1321",
      "1322",
      "1323",
      "1324",
      "1325",
      "1330",
      "1331",
      "1332",
      "1340",
      "1341",
      "1342",
      "1343",
      "1344",
      "1345",
      "1346",
      "1347",
      "1348",
      "1349",
      "1350",
      "1351",
      "1360",
      "1361",
      "1362",
      "7800",
      "7801",
      "7802",
      "7803",
      "7804",
      "7810",
      "7820",
      "7821",
      "7822",
      "7830",
      "7840",
      "7841",
      "7850",
      "7851",
      "7860",
      "7861",
      "7870",
      "1700",
      "1701",
      "1702",
      "1703",
      "1704",
      "1710",
      "1711",
      "1712",
      "1720",
      "1721",
      "1722",
      "1723",
      "1730",
      "1740",
      "1741",
      "1742",
      "1743",
      "1744",
      "1745",
      "1747",
      "1748",
      "1750",
      "1751",
      "8013",
      "8100",
      "8101",
      "8102",
      "8110",
      "8120",
      "8121",
      "8130",
      "8131",
    ],
    country: "bd",
  },
  results: {
    "1000": [
      {
        postal_code: "1000",
        country_code: "BD",
        latitude: "23.72900000",
        longitude: "90.41120000",
        city: "Dhaka GPO",
        state: "Dhaka Division",
        city_en: "Dhaka GPO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1100": [
      {
        postal_code: "1100",
        country_code: "BD",
        latitude: "23.99960000",
        longitude: "90.42220000",
        city: "Dhaka Sadar HO",
        state: "Dhaka Division",
        city_en: "Dhaka Sadar HO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1203": [
      {
        postal_code: "1203",
        country_code: "BD",
        latitude: "23.74150000",
        longitude: "90.42760000",
        city: "Wari TSO",
        state: "Dhaka Division",
        city_en: "Wari TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1204": [
      {
        postal_code: "1204",
        country_code: "BD",
        latitude: "23.70110000",
        longitude: "90.42630000",
        city: "Gendaria TSO",
        state: "Dhaka Division",
        city_en: "Gendaria TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1205": [
      {
        postal_code: "1205",
        country_code: "BD",
        latitude: "23.74330000",
        longitude: "90.38410000",
        city: "New Market TSO",
        state: "Dhaka Division",
        city_en: "New Market TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1206": [
      {
        postal_code: "1206",
        country_code: "BD",
        latitude: "23.81790000",
        longitude: "90.41030000",
        city: "Dhaka CantonmentTSO",
        state: "Dhaka Division",
        city_en: "Dhaka CantonmentTSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1207": [
      {
        postal_code: "1207",
        country_code: "BD",
        latitude: "23.77010000",
        longitude: "90.36280000",
        city: "Mohammadpur Housing",
        state: "Dhaka Division",
        city_en: "Mohammadpur Housing",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1208": [
      {
        postal_code: "1208",
        country_code: "BD",
        latitude: "23.75910000",
        longitude: "90.40030000",
        city: "Dhaka Politechnic",
        state: "Dhaka Division",
        city_en: "Dhaka Politechnic",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1209": [
      {
        postal_code: "1209",
        country_code: "BD",
        latitude: "23.75520000",
        longitude: "90.37310000",
        city: "Jigatala TSO",
        state: "Dhaka Division",
        city_en: "Jigatala TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1211": [
      {
        postal_code: "1211",
        country_code: "BD",
        latitude: "23.81960000",
        longitude: "90.36400000",
        city: "Posta TSO",
        state: "Dhaka Division",
        city_en: "Posta TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1212": [
      {
        postal_code: "1212",
        country_code: "BD",
        latitude: "23.79160000",
        longitude: "90.41520000",
        city: "Gulshan Model Town",
        state: "Dhaka Division",
        city_en: "Gulshan Model Town",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1213": [
      {
        postal_code: "1213",
        country_code: "BD",
        latitude: "23.79310000",
        longitude: "90.40480000",
        city: "Banani TSO",
        state: "Dhaka Division",
        city_en: "Banani TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1214": [
      {
        postal_code: "1214",
        country_code: "BD",
        latitude: "23.74180000",
        longitude: "90.42770000",
        city: "Basabo TSO",
        state: "Dhaka Division",
        city_en: "Basabo TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1215": [
      {
        postal_code: "1215",
        country_code: "BD",
        latitude: "23.76870000",
        longitude: "90.39010000",
        city: "Tejgaon TSO",
        state: "Dhaka Division",
        city_en: "Tejgaon TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1216": [
      {
        postal_code: "1216",
        country_code: "BD",
        latitude: "23.82190000",
        longitude: "90.36570000",
        city: "Mirpur TSO",
        state: "Dhaka Division",
        city_en: "Mirpur TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1217": [
      {
        postal_code: "1217",
        country_code: "BD",
        latitude: "23.72600000",
        longitude: "90.42510000",
        city: "Shantinagr TSO",
        state: "Dhaka Division",
        city_en: "Shantinagr TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1219": [
      {
        postal_code: "1219",
        country_code: "BD",
        latitude: "23.75180000",
        longitude: "90.42540000",
        city: "KhilgaonTSO",
        state: "Dhaka Division",
        city_en: "KhilgaonTSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1222": [
      {
        postal_code: "1222",
        country_code: "BD",
        latitude: "23.90720000",
        longitude: "90.45990000",
        city: "BangabhabanTSO",
        state: "Dhaka Division",
        city_en: "BangabhabanTSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1223": [
      {
        postal_code: "1223",
        country_code: "BD",
        latitude: "23.88220000",
        longitude: "90.45760000",
        city: "DilkushaTSO",
        state: "Dhaka Division",
        city_en: "DilkushaTSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1225": [
      {
        postal_code: "1225",
        country_code: "BD",
        latitude: "23.76170000",
        longitude: "90.37840000",
        city: "Sangsad BhabanTSO",
        state: "Dhaka Division",
        city_en: "Sangsad BhabanTSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1229": [
      {
        postal_code: "1229",
        country_code: "BD",
        latitude: "23.85150000",
        longitude: "90.40300000",
        city: "KhilkhetTSO",
        state: "Dhaka Division",
        city_en: "KhilkhetTSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1230": [
      {
        postal_code: "1230",
        country_code: "BD",
        latitude: "23.86670000",
        longitude: "90.40000000",
        city: "Uttara Model TwonTSO",
        state: "Dhaka Division",
        city_en: "Uttara Model TwonTSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1232": [
      {
        postal_code: "1232",
        country_code: "BD",
        latitude: "23.71170000",
        longitude: "90.44630000",
        city: "Dhania TSO",
        state: "Dhaka Division",
        city_en: "Dhania TSO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1310": [
      {
        postal_code: "1310",
        country_code: "BD",
        latitude: "23.72230000",
        longitude: "90.31100000",
        city: "Keraniganj",
        state: "Dhaka Division",
        city_en: "Keraniganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1311": [
      {
        postal_code: "1311",
        country_code: "BD",
        latitude: "23.72230000",
        longitude: "90.31100000",
        city: "Dhaka Jute Mills",
        state: "Dhaka Division",
        city_en: "Dhaka Jute Mills",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1312": [
      {
        postal_code: "1312",
        country_code: "BD",
        latitude: "23.71670000",
        longitude: "90.35000000",
        city: "Ati",
        state: "Dhaka Division",
        city_en: "Ati",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1313": [
      {
        postal_code: "1313",
        country_code: "BD",
        latitude: "23.72790000",
        longitude: "90.27210000",
        city: "Kalatia",
        state: "Dhaka Division",
        city_en: "Kalatia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1320": [
      {
        postal_code: "1320",
        country_code: "BD",
        latitude: "23.66300000",
        longitude: "90.15930000",
        city: "Nawabganj",
        state: "Dhaka Division",
        city_en: "Nawabganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1321": [
      {
        postal_code: "1321",
        country_code: "BD",
        latitude: "23.65510000",
        longitude: "90.10550000",
        city: "Hasnabad",
        state: "Dhaka Division",
        city_en: "Hasnabad",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1322": [
      {
        postal_code: "1322",
        country_code: "BD",
        latitude: "23.88330000",
        longitude: "90.53330000",
        city: "Daudpur",
        state: "Dhaka Division",
        city_en: "Daudpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1323": [
      {
        postal_code: "1323",
        country_code: "BD",
        latitude: "23.65030000",
        longitude: "90.21850000",
        city: "Agla",
        state: "Dhaka Division",
        city_en: "Agla",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1324": [
      {
        postal_code: "1324",
        country_code: "BD",
        latitude: "23.62980000",
        longitude: "90.13130000",
        city: "Khalpar",
        state: "Dhaka Division",
        city_en: "Khalpar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1325": [
      {
        postal_code: "1325",
        country_code: "BD",
        latitude: "23.61890000",
        longitude: "90.22400000",
        city: "Churain",
        state: "Dhaka Division",
        city_en: "Churain",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1330": [
      {
        postal_code: "1330",
        country_code: "BD",
        latitude: "23.62150000",
        longitude: "90.12410000",
        city: "Joypara",
        state: "Dhaka Division",
        city_en: "Joypara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1331": [
      {
        postal_code: "1331",
        country_code: "BD",
        latitude: "23.54120000",
        longitude: "90.25380000",
        city: "Palamganj",
        state: "Dhaka Division",
        city_en: "Palamganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1332": [
      {
        postal_code: "1332",
        country_code: "BD",
        latitude: "23.54120000",
        longitude: "90.25380000",
        city: "Narisha",
        state: "Dhaka Division",
        city_en: "Narisha",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1340": [
      {
        postal_code: "1340",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "Savar",
        state: "Dhaka Division",
        city_en: "Savar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1341": [
      {
        postal_code: "1341",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "Dairy Farm",
        state: "Dhaka Division",
        city_en: "Dairy Farm",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1342": [
      {
        postal_code: "1342",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "Jahangirnagar Univer",
        state: "Dhaka Division",
        city_en: "Jahangirnagar Univer",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1343": [
      {
        postal_code: "1343",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "Saver P.A.T.C",
        state: "Dhaka Division",
        city_en: "Saver P.A.T.C",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1344": [
      {
        postal_code: "1344",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "Savar Canttonment",
        state: "Dhaka Division",
        city_en: "Savar Canttonment",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1345": [
      {
        postal_code: "1345",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "Shimulia",
        state: "Dhaka Division",
        city_en: "Shimulia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1346": [
      {
        postal_code: "1346",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "Kashem Cotton Mills",
        state: "Dhaka Division",
        city_en: "Kashem Cotton Mills",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1347": [
      {
        postal_code: "1347",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "Rajphulbaria",
        state: "Dhaka Division",
        city_en: "Rajphulbaria",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1348": [
      {
        postal_code: "1348",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "Amin Bazar",
        state: "Dhaka Division",
        city_en: "Amin Bazar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1349": [
      {
        postal_code: "1349",
        country_code: "BD",
        latitude: "23.84860000",
        longitude: "90.25000000",
        city: "EPZ",
        state: "Dhaka Division",
        city_en: "EPZ",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1350": [
      {
        postal_code: "1350",
        country_code: "BD",
        latitude: "23.91220000",
        longitude: "90.26830000",
        city: "Dhamrai",
        state: "Dhaka Division",
        city_en: "Dhamrai",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1351": [
      {
        postal_code: "1351",
        country_code: "BD",
        latitude: "23.99940000",
        longitude: "90.80990000",
        city: "Kamalpur",
        state: "Dhaka Division",
        city_en: "Kamalpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1360": [
      {
        postal_code: "1360",
        country_code: "BD",
        latitude: "23.70990000",
        longitude: "90.45460000",
        city: "Demra",
        state: "Dhaka Division",
        city_en: "Demra",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1361": [
      {
        postal_code: "1361",
        country_code: "BD",
        latitude: "23.84290000",
        longitude: "90.32440000",
        city: "Sarulia",
        state: "Dhaka Division",
        city_en: "Sarulia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1362": [
      {
        postal_code: "1362",
        country_code: "BD",
        latitude: "23.71210000",
        longitude: "90.45980000",
        city: "Matuail",
        state: "Dhaka Division",
        city_en: "Matuail",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Dhaka",
        province_code: "3026",
      },
    ],
    "1700": [
      {
        postal_code: "1700",
        country_code: "BD",
        latitude: "23.98740000",
        longitude: "90.40520000",
        city: "Gazipur Sadar",
        state: "Dhaka Division",
        city_en: "Gazipur Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1701": [
      {
        postal_code: "1701",
        country_code: "BD",
        latitude: "23.98740000",
        longitude: "90.40520000",
        city: "B.R.R",
        state: "Dhaka Division",
        city_en: "B.R.R",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1702": [
      {
        postal_code: "1702",
        country_code: "BD",
        latitude: "23.98740000",
        longitude: "90.40520000",
        city: "Chandna",
        state: "Dhaka Division",
        city_en: "Chandna",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1703": [
      {
        postal_code: "1703",
        country_code: "BD",
        latitude: "23.98740000",
        longitude: "90.40520000",
        city: "B.O.F",
        state: "Dhaka Division",
        city_en: "B.O.F",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1704": [
      {
        postal_code: "1704",
        country_code: "BD",
        latitude: "23.98740000",
        longitude: "90.40520000",
        city: "National University",
        state: "Dhaka Division",
        city_en: "National University",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1710": [
      {
        postal_code: "1710",
        country_code: "BD",
        latitude: "24.09420000",
        longitude: "90.48580000",
        city: "Monnunagar",
        state: "Dhaka Division",
        city_en: "Monnunagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1711": [
      {
        postal_code: "1711",
        country_code: "BD",
        latitude: "24.09420000",
        longitude: "90.48580000",
        city: "Nishat Nagar",
        state: "Dhaka Division",
        city_en: "Nishat Nagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1712": [
      {
        postal_code: "1712",
        country_code: "BD",
        latitude: "24.09420000",
        longitude: "90.48580000",
        city: "Ershad Nagar",
        state: "Dhaka Division",
        city_en: "Ershad Nagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1720": [
      {
        postal_code: "1720",
        country_code: "BD",
        latitude: "23.92300000",
        longitude: "90.56550000",
        city: "Kaliganj",
        state: "Dhaka Division",
        city_en: "Kaliganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1721": [
      {
        postal_code: "1721",
        country_code: "BD",
        latitude: "23.93870000",
        longitude: "90.47440000",
        city: "Pubail",
        state: "Dhaka Division",
        city_en: "Pubail",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1722": [
      {
        postal_code: "1722",
        country_code: "BD",
        latitude: "23.91930000",
        longitude: "90.61120000",
        city: "Santanpara",
        state: "Dhaka Division",
        city_en: "Santanpara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1723": [
      {
        postal_code: "1723",
        country_code: "BD",
        latitude: "23.92700000",
        longitude: "90.55040000",
        city: "Vaoal Jamalpur",
        state: "Dhaka Division",
        city_en: "Vaoal Jamalpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1730": [
      {
        postal_code: "1730",
        country_code: "BD",
        latitude: "24.09420000",
        longitude: "90.48580000",
        city: "kapashia",
        state: "Dhaka Division",
        city_en: "kapashia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1740": [
      {
        postal_code: "1740",
        country_code: "BD",
        latitude: "24.43000000",
        longitude: "90.53420000",
        city: "Sreepur",
        state: "Dhaka Division",
        city_en: "Sreepur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1741": [
      {
        postal_code: "1741",
        country_code: "BD",
        latitude: "24.62330000",
        longitude: "90.57820000",
        city: "Rajendrapur",
        state: "Dhaka Division",
        city_en: "Rajendrapur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1742": [
      {
        postal_code: "1742",
        country_code: "BD",
        latitude: "24.43000000",
        longitude: "90.53420000",
        city: "Rajendrapur Canttome",
        state: "Dhaka Division",
        city_en: "Rajendrapur Canttome",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1743": [
      {
        postal_code: "1743",
        country_code: "BD",
        latitude: "24.43000000",
        longitude: "90.53420000",
        city: "Barmi",
        state: "Dhaka Division",
        city_en: "Barmi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1744": [
      {
        postal_code: "1744",
        country_code: "BD",
        latitude: "24.23680000",
        longitude: "90.49030000",
        city: "Satkhamair",
        state: "Dhaka Division",
        city_en: "Satkhamair",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1745": [
      {
        postal_code: "1745",
        country_code: "BD",
        latitude: "24.43000000",
        longitude: "90.53420000",
        city: "Kawraid",
        state: "Dhaka Division",
        city_en: "Kawraid",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1747": [
      {
        postal_code: "1747",
        country_code: "BD",
        latitude: "24.43000000",
        longitude: "90.53420000",
        city: "Bashamur",
        state: "Dhaka Division",
        city_en: "Bashamur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1748": [
      {
        postal_code: "1748",
        country_code: "BD",
        latitude: "24.43000000",
        longitude: "90.53420000",
        city: "Boubi",
        state: "Dhaka Division",
        city_en: "Boubi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1750": [
      {
        postal_code: "1750",
        country_code: "BD",
        latitude: "24.03110000",
        longitude: "90.27600000",
        city: "Kaliakaar",
        state: "Dhaka Division",
        city_en: "Kaliakaar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "1751": [
      {
        postal_code: "1751",
        country_code: "BD",
        latitude: "24.03110000",
        longitude: "90.27600000",
        city: "Safipur",
        state: "Dhaka Division",
        city_en: "Safipur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gazipur",
        province_code: "3033",
      },
    ],
    "7800": [
      {
        postal_code: "7800",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "89.78330000",
        city: "Faridpursadar",
        state: "Dhaka Division",
        city_en: "Faridpursadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7801": [
      {
        postal_code: "7801",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "89.78330000",
        city: "Kanaipur",
        state: "Dhaka Division",
        city_en: "Kanaipur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7802": [
      {
        postal_code: "7802",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "89.78330000",
        city: "Ambikapur",
        state: "Dhaka Division",
        city_en: "Ambikapur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7803": [
      {
        postal_code: "7803",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "89.78330000",
        city: "Baitulaman Politecni",
        state: "Dhaka Division",
        city_en: "Baitulaman Politecni",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7804": [
      {
        postal_code: "7804",
        country_code: "BD",
        latitude: "23.55000000",
        longitude: "89.78330000",
        city: "Shriangan",
        state: "Dhaka Division",
        city_en: "Shriangan",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7810": [
      {
        postal_code: "7810",
        country_code: "BD",
        latitude: "23.42240000",
        longitude: "89.80670000",
        city: "Charbadrashan",
        state: "Dhaka Division",
        city_en: "Charbadrashan",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7820": [
      {
        postal_code: "7820",
        country_code: "BD",
        latitude: "23.42240000",
        longitude: "89.80670000",
        city: "Sadarpur",
        state: "Dhaka Division",
        city_en: "Sadarpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7821": [
      {
        postal_code: "7821",
        country_code: "BD",
        latitude: "23.42240000",
        longitude: "89.80670000",
        city: "Hat Krishapur",
        state: "Dhaka Division",
        city_en: "Hat Krishapur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7822": [
      {
        postal_code: "7822",
        country_code: "BD",
        latitude: "23.42240000",
        longitude: "89.80670000",
        city: "Bishwa jaker Manjil",
        state: "Dhaka Division",
        city_en: "Bishwa jaker Manjil",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7830": [
      {
        postal_code: "7830",
        country_code: "BD",
        latitude: "23.39190000",
        longitude: "89.98390000",
        city: "Bhanga",
        state: "Dhaka Division",
        city_en: "Bhanga",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7840": [
      {
        postal_code: "7840",
        country_code: "BD",
        latitude: "23.48880000",
        longitude: "89.87710000",
        city: "Nagarkanda",
        state: "Dhaka Division",
        city_en: "Nagarkanda",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7841": [
      {
        postal_code: "7841",
        country_code: "BD",
        latitude: "23.48880000",
        longitude: "89.87710000",
        city: "Talma",
        state: "Dhaka Division",
        city_en: "Talma",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7850": [
      {
        postal_code: "7850",
        country_code: "BD",
        latitude: "23.42240000",
        longitude: "89.80670000",
        city: "Madukhali",
        state: "Dhaka Division",
        city_en: "Madukhali",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7851": [
      {
        postal_code: "7851",
        country_code: "BD",
        latitude: "23.42240000",
        longitude: "89.80670000",
        city: "Kamarkali",
        state: "Dhaka Division",
        city_en: "Kamarkali",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7860": [
      {
        postal_code: "7860",
        country_code: "BD",
        latitude: "23.39210000",
        longitude: "89.68310000",
        city: "Boalmari",
        state: "Dhaka Division",
        city_en: "Boalmari",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7861": [
      {
        postal_code: "7861",
        country_code: "BD",
        latitude: "23.39210000",
        longitude: "89.68310000",
        city: "Rupatpat",
        state: "Dhaka Division",
        city_en: "Rupatpat",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "7870": [
      {
        postal_code: "7870",
        country_code: "BD",
        latitude: "23.28900000",
        longitude: "89.70600000",
        city: "Alfadanga",
        state: "Dhaka Division",
        city_en: "Alfadanga",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Faridpur",
        province_code: "3029",
      },
    ],
    "8013": [
      {
        postal_code: "8013",
        country_code: "BD",
        latitude: "23.23280000",
        longitude: "90.42420000",
        city: "Chandradighalia",
        state: "Dhaka Division",
        city_en: "Chandradighalia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8100": [
      {
        postal_code: "8100",
        country_code: "BD",
        latitude: "23.07130000",
        longitude: "89.83450000",
        city: "Gopalganj Sadar",
        state: "Dhaka Division",
        city_en: "Gopalganj Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8101": [
      {
        postal_code: "8101",
        country_code: "BD",
        latitude: "23.07130000",
        longitude: "89.83450000",
        city: "Ulpur",
        state: "Dhaka Division",
        city_en: "Ulpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8102": [
      {
        postal_code: "8102",
        country_code: "BD",
        latitude: "23.07130000",
        longitude: "89.83450000",
        city: "Barfa",
        state: "Dhaka Division",
        city_en: "Barfa",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8110": [
      {
        postal_code: "8110",
        country_code: "BD",
        latitude: "23.15280000",
        longitude: "89.89740000",
        city: "Kotalipara",
        state: "Dhaka Division",
        city_en: "Kotalipara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8120": [
      {
        postal_code: "8120",
        country_code: "BD",
        latitude: "22.89980000",
        longitude: "89.90330000",
        city: "Tungipara",
        state: "Dhaka Division",
        city_en: "Tungipara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8121": [
      {
        postal_code: "8121",
        country_code: "BD",
        latitude: "22.89270000",
        longitude: "89.89700000",
        city: "Patgati",
        state: "Dhaka Division",
        city_en: "Patgati",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8130": [
      {
        postal_code: "8130",
        country_code: "BD",
        latitude: "23.23570000",
        longitude: "89.72050000",
        city: "Kashiani",
        state: "Dhaka Division",
        city_en: "Kashiani",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
    "8131": [
      {
        postal_code: "8131",
        country_code: "BD",
        latitude: "23.23570000",
        longitude: "89.72050000",
        city: "Ramdia College",
        state: "Dhaka Division",
        city_en: "Ramdia College",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Gopalganj",
        province_code: "3035",
      },
    ],
  },
};

export default postOffices1;
