import { PostOfficeInfo } from "./IPostOfficeInfo";

const postOffices3: PostOfficeInfo = {
  query: {
    codes: [
      "1414",
      "1420",
      "1421",
      "1430",
      "1431",
      "1432",
      "1440",
      "1441",
      "1442",
      "1450",
      "1451",
      "1460",
      "1461",
      "1462",
      "1463",
      "1464",
      "1600",
      "1601",
      "1602",
      "1603",
      "1604",
      "1605",
      "1610",
      "1611",
      "1612",
      "1613",
      "1620",
      "1630",
      "1631",
      "1632",
      "1640",
      "1650",
      "1651",
      "1652",
      "7700",
      "7710",
      "7711",
      "7720",
      "7721",
      "7722",
      "7723",
      "7730",
      "7731",
      "8000",
      "8001",
      "8002",
      "8010",
      "8020",
      "8021",
      "8022",
      "8023",
      "8024",
      "8030",
      "8040",
      "8050",
      "1900",
      "1901",
      "1902",
      "1903",
      "1904",
      "1910",
      "1911",
      "1912",
      "1913",
      "1914",
      "1915",
      "1920",
      "1930",
      "1936",
      "1937",
      "1938",
      "1940",
      "1941",
      "1942",
      "1943",
      "1944",
      "1945",
      "1950",
      "1951",
      "1960",
      "1970",
      "1971",
      "1972",
      "1973",
      "1974",
      "1975",
      "1976",
      "1977",
      "1980",
      "1981",
      "1982",
      "1983",
      "1984",
      "1990",
      "1991",
      "1992",
      "1996",
      "1997",
      "2000",
      "2001",
    ],
    country: "bd",
  },
  results: {
    "1414": [
      {
        postal_code: "1414",
        country_code: "BD",
        latitude: "23.58580000",
        longitude: "90.52200000",
        city: "Madanganj",
        state: "Dhaka Division",
        city_en: "Madanganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1420": [
      {
        postal_code: "1420",
        country_code: "BD",
        latitude: "23.65000000",
        longitude: "90.49000000",
        city: "Fatullah",
        state: "Dhaka Division",
        city_en: "Fatullah",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1421": [
      {
        postal_code: "1421",
        country_code: "BD",
        latitude: "23.65000000",
        longitude: "90.49000000",
        city: "Fatulla Bazar",
        state: "Dhaka Division",
        city_en: "Fatulla Bazar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1430": [
      {
        postal_code: "1430",
        country_code: "BD",
        latitude: "23.71970000",
        longitude: "90.56340000",
        city: "Siddirganj",
        state: "Dhaka Division",
        city_en: "Siddirganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1431": [
      {
        postal_code: "1431",
        country_code: "BD",
        latitude: "23.71970000",
        longitude: "90.56340000",
        city: "Adamjeenagar",
        state: "Dhaka Division",
        city_en: "Adamjeenagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1432": [
      {
        postal_code: "1432",
        country_code: "BD",
        latitude: "23.71970000",
        longitude: "90.56340000",
        city: "LN Mills",
        state: "Dhaka Division",
        city_en: "LN Mills",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1440": [
      {
        postal_code: "1440",
        country_code: "BD",
        latitude: "23.71970000",
        longitude: "90.56340000",
        city: "Baidder Bazar",
        state: "Dhaka Division",
        city_en: "Baidder Bazar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1441": [
      {
        postal_code: "1441",
        country_code: "BD",
        latitude: "23.71970000",
        longitude: "90.56340000",
        city: "Bara Nagar",
        state: "Dhaka Division",
        city_en: "Bara Nagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1442": [
      {
        postal_code: "1442",
        country_code: "BD",
        latitude: "23.71970000",
        longitude: "90.56340000",
        city: "Barodi",
        state: "Dhaka Division",
        city_en: "Barodi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1450": [
      {
        postal_code: "1450",
        country_code: "BD",
        latitude: "23.79410000",
        longitude: "90.65750000",
        city: "Araihazar",
        state: "Dhaka Division",
        city_en: "Araihazar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1451": [
      {
        postal_code: "1451",
        country_code: "BD",
        latitude: "23.80570000",
        longitude: "90.71030000",
        city: "Gopaldi",
        state: "Dhaka Division",
        city_en: "Gopaldi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1460": [
      {
        postal_code: "1460",
        country_code: "BD",
        latitude: "23.79860000",
        longitude: "90.54750000",
        city: "Rupganj",
        state: "Dhaka Division",
        city_en: "Rupganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1461": [
      {
        postal_code: "1461",
        country_code: "BD",
        latitude: "23.83100000",
        longitude: "90.55800000",
        city: "Kanchan",
        state: "Dhaka Division",
        city_en: "Kanchan",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1462": [
      {
        postal_code: "1462",
        country_code: "BD",
        latitude: "23.77750000",
        longitude: "90.55930000",
        city: "Bhulta",
        state: "Dhaka Division",
        city_en: "Bhulta",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1463": [
      {
        postal_code: "1463",
        country_code: "BD",
        latitude: "23.79860000",
        longitude: "90.54750000",
        city: "Nagri",
        state: "Dhaka Division",
        city_en: "Nagri",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1464": [
      {
        postal_code: "1464",
        country_code: "BD",
        latitude: "23.78710000",
        longitude: "90.52520000",
        city: "Murapara",
        state: "Dhaka Division",
        city_en: "Murapara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narayanganj",
        province_code: "3067",
      },
    ],
    "1600": [
      {
        postal_code: "1600",
        country_code: "BD",
        latitude: "23.92820000",
        longitude: "90.69940000",
        city: "Narshingdi Sadar",
        state: "Dhaka Division",
        city_en: "Narshingdi Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1601": [
      {
        postal_code: "1601",
        country_code: "BD",
        latitude: "23.92820000",
        longitude: "90.69940000",
        city: "UMC Jute Mills",
        state: "Dhaka Division",
        city_en: "UMC Jute Mills",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1602": [
      {
        postal_code: "1602",
        country_code: "BD",
        latitude: "23.92820000",
        longitude: "90.69940000",
        city: "Narshingdi College",
        state: "Dhaka Division",
        city_en: "Narshingdi College",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1603": [
      {
        postal_code: "1603",
        country_code: "BD",
        latitude: "23.89830000",
        longitude: "90.66150000",
        city: "Panchdona",
        state: "Dhaka Division",
        city_en: "Panchdona",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1604": [
      {
        postal_code: "1604",
        country_code: "BD",
        latitude: "23.99900000",
        longitude: "90.69250000",
        city: "Madhabdi",
        state: "Dhaka Division",
        city_en: "Madhabdi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1605": [
      {
        postal_code: "1605",
        country_code: "BD",
        latitude: "23.88740000",
        longitude: "90.74420000",
        city: "Karimpur",
        state: "Dhaka Division",
        city_en: "Karimpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1610": [
      {
        postal_code: "1610",
        country_code: "BD",
        latitude: "23.95000000",
        longitude: "90.62500000",
        city: "Palash",
        state: "Dhaka Division",
        city_en: "Palash",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1611": [
      {
        postal_code: "1611",
        country_code: "BD",
        latitude: "23.94560000",
        longitude: "90.62770000",
        city: "Ghorashal Urea Facto",
        state: "Dhaka Division",
        city_en: "Ghorashal Urea Facto",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1612": [
      {
        postal_code: "1612",
        country_code: "BD",
        latitude: "23.94560000",
        longitude: "90.62770000",
        city: "Char Sindhur",
        state: "Dhaka Division",
        city_en: "Char Sindhur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1613": [
      {
        postal_code: "1613",
        country_code: "BD",
        latitude: "23.94130000",
        longitude: "90.63040000",
        city: "Ghorashal",
        state: "Dhaka Division",
        city_en: "Ghorashal",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1620": [
      {
        postal_code: "1620",
        country_code: "BD",
        latitude: "24.03940000",
        longitude: "90.73920000",
        city: "Shibpur",
        state: "Dhaka Division",
        city_en: "Shibpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1630": [
      {
        postal_code: "1630",
        country_code: "BD",
        latitude: "24.01860000",
        longitude: "90.71290000",
        city: "Raypura",
        state: "Dhaka Division",
        city_en: "Raypura",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1631": [
      {
        postal_code: "1631",
        country_code: "BD",
        latitude: "24.01860000",
        longitude: "90.71290000",
        city: "Bazar Hasnabad",
        state: "Dhaka Division",
        city_en: "Bazar Hasnabad",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1632": [
      {
        postal_code: "1632",
        country_code: "BD",
        latitude: "24.01860000",
        longitude: "90.71290000",
        city: "Radhaganj bazar",
        state: "Dhaka Division",
        city_en: "Radhaganj bazar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1640": [
      {
        postal_code: "1640",
        country_code: "BD",
        latitude: "24.10350000",
        longitude: "90.84580000",
        city: "Belabo",
        state: "Dhaka Division",
        city_en: "Belabo",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1650": [
      {
        postal_code: "1650",
        country_code: "BD",
        latitude: "24.11550000",
        longitude: "90.72710000",
        city: "Monohordi",
        state: "Dhaka Division",
        city_en: "Monohordi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1651": [
      {
        postal_code: "1651",
        country_code: "BD",
        latitude: "24.10070000",
        longitude: "90.70300000",
        city: "Hatirdia",
        state: "Dhaka Division",
        city_en: "Hatirdia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1652": [
      {
        postal_code: "1652",
        country_code: "BD",
        latitude: "24.15080000",
        longitude: "90.76080000",
        city: "Katabaria",
        state: "Dhaka Division",
        city_en: "Katabaria",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Narshingdi",
        province_code: "3068",
      },
    ],
    "1900": [
      {
        postal_code: "1900",
        country_code: "BD",
        latitude: "24.35510000",
        longitude: "90.03860000",
        city: "Tangail Sadar",
        state: "Dhaka Division",
        city_en: "Tangail Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1901": [
      {
        postal_code: "1901",
        country_code: "BD",
        latitude: "24.35510000",
        longitude: "90.03860000",
        city: "Kagmari",
        state: "Dhaka Division",
        city_en: "Kagmari",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1902": [
      {
        postal_code: "1902",
        country_code: "BD",
        latitude: "24.35510000",
        longitude: "90.03860000",
        city: "Santosh",
        state: "Dhaka Division",
        city_en: "Santosh",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1903": [
      {
        postal_code: "1903",
        country_code: "BD",
        latitude: "24.35510000",
        longitude: "90.03860000",
        city: "Korotia",
        state: "Dhaka Division",
        city_en: "Korotia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1904": [
      {
        postal_code: "1904",
        country_code: "BD",
        latitude: "24.35510000",
        longitude: "90.03860000",
        city: "Purabari",
        state: "Dhaka Division",
        city_en: "Purabari",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1910": [
      {
        postal_code: "1910",
        country_code: "BD",
        latitude: "24.15970000",
        longitude: "89.96210000",
        city: "Delduar",
        state: "Dhaka Division",
        city_en: "Delduar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1911": [
      {
        postal_code: "1911",
        country_code: "BD",
        latitude: "23.98540000",
        longitude: "90.06620000",
        city: "Jangalia",
        state: "Dhaka Division",
        city_en: "Jangalia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1912": [
      {
        postal_code: "1912",
        country_code: "BD",
        latitude: "23.86670000",
        longitude: "89.95000000",
        city: "Patharail",
        state: "Dhaka Division",
        city_en: "Patharail",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1913": [
      {
        postal_code: "1913",
        country_code: "BD",
        latitude: "24.00390000",
        longitude: "89.99280000",
        city: "Elasin",
        state: "Dhaka Division",
        city_en: "Elasin",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1914": [
      {
        postal_code: "1914",
        country_code: "BD",
        latitude: "24.00390000",
        longitude: "89.99280000",
        city: "Hinga Nagar",
        state: "Dhaka Division",
        city_en: "Hinga Nagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1915": [
      {
        postal_code: "1915",
        country_code: "BD",
        latitude: "24.00390000",
        longitude: "89.99280000",
        city: "Lowhati",
        state: "Dhaka Division",
        city_en: "Lowhati",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1920": [
      {
        postal_code: "1920",
        country_code: "BD",
        latitude: "24.28570000",
        longitude: "90.00030000",
        city: "Basail",
        state: "Dhaka Division",
        city_en: "Basail",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1930": [
      {
        postal_code: "1930",
        country_code: "BD",
        latitude: "24.05780000",
        longitude: "89.87700000",
        city: "Kashkawlia",
        state: "Dhaka Division",
        city_en: "Kashkawlia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1936": [
      {
        postal_code: "1936",
        country_code: "BD",
        latitude: "24.05780000",
        longitude: "89.87700000",
        city: "Nagarpur",
        state: "Dhaka Division",
        city_en: "Nagarpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1937": [
      {
        postal_code: "1937",
        country_code: "BD",
        latitude: "24.05780000",
        longitude: "89.87700000",
        city: "Dhuburia",
        state: "Dhaka Division",
        city_en: "Dhuburia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1938": [
      {
        postal_code: "1938",
        country_code: "BD",
        latitude: "24.05780000",
        longitude: "89.87700000",
        city: "Salimabad",
        state: "Dhaka Division",
        city_en: "Salimabad",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1940": [
      {
        postal_code: "1940",
        country_code: "BD",
        latitude: "24.10290000",
        longitude: "90.09840000",
        city: "Mirzapur",
        state: "Dhaka Division",
        city_en: "Mirzapur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1941": [
      {
        postal_code: "1941",
        country_code: "BD",
        latitude: "24.09260000",
        longitude: "90.16230000",
        city: "Gorai",
        state: "Dhaka Division",
        city_en: "Gorai",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1942": [
      {
        postal_code: "1942",
        country_code: "BD",
        latitude: "24.09770000",
        longitude: "90.13030000",
        city: "M.C. College",
        state: "Dhaka Division",
        city_en: "M.C. College",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1943": [
      {
        postal_code: "1943",
        country_code: "BD",
        latitude: "24.09770000",
        longitude: "90.13030000",
        city: "Warri paikpara",
        state: "Dhaka Division",
        city_en: "Warri paikpara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1944": [
      {
        postal_code: "1944",
        country_code: "BD",
        latitude: "24.09770000",
        longitude: "90.13030000",
        city: "Jarmuki",
        state: "Dhaka Division",
        city_en: "Jarmuki",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1945": [
      {
        postal_code: "1945",
        country_code: "BD",
        latitude: "24.09770000",
        longitude: "90.13030000",
        city: "Mohera",
        state: "Dhaka Division",
        city_en: "Mohera",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1950": [
      {
        postal_code: "1950",
        country_code: "BD",
        latitude: "24.31990000",
        longitude: "90.16940000",
        city: "Sakhipur",
        state: "Dhaka Division",
        city_en: "Sakhipur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1951": [
      {
        postal_code: "1951",
        country_code: "BD",
        latitude: "24.31990000",
        longitude: "90.16940000",
        city: "Kochua",
        state: "Dhaka Division",
        city_en: "Kochua",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1960": [
      {
        postal_code: "1960",
        country_code: "BD",
        latitude: "24.46040000",
        longitude: "89.87270000",
        city: "Bhuapur",
        state: "Dhaka Division",
        city_en: "Bhuapur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1970": [
      {
        postal_code: "1970",
        country_code: "BD",
        latitude: "24.38240000",
        longitude: "90.00060000",
        city: "Kalihati",
        state: "Dhaka Division",
        city_en: "Kalihati",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1971": [
      {
        postal_code: "1971",
        country_code: "BD",
        latitude: "24.40000000",
        longitude: "90.03330000",
        city: "Rajafair",
        state: "Dhaka Division",
        city_en: "Rajafair",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1972": [
      {
        postal_code: "1972",
        country_code: "BD",
        latitude: "24.34510000",
        longitude: "90.04940000",
        city: "Nagbari",
        state: "Dhaka Division",
        city_en: "Nagbari",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1973": [
      {
        postal_code: "1973",
        country_code: "BD",
        latitude: "24.38240000",
        longitude: "90.00060000",
        city: "Ballabazar",
        state: "Dhaka Division",
        city_en: "Ballabazar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1974": [
      {
        postal_code: "1974",
        country_code: "BD",
        latitude: "24.38240000",
        longitude: "90.00060000",
        city: "Elinga",
        state: "Dhaka Division",
        city_en: "Elinga",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1975": [
      {
        postal_code: "1975",
        country_code: "BD",
        latitude: "24.38240000",
        longitude: "90.00060000",
        city: "Palisha",
        state: "Dhaka Division",
        city_en: "Palisha",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1976": [
      {
        postal_code: "1976",
        country_code: "BD",
        latitude: "24.38240000",
        longitude: "90.00060000",
        city: "Nagarbari SO",
        state: "Dhaka Division",
        city_en: "Nagarbari SO",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1977": [
      {
        postal_code: "1977",
        country_code: "BD",
        latitude: "24.40220000",
        longitude: "89.91900000",
        city: "Nagarbari",
        state: "Dhaka Division",
        city_en: "Nagarbari",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1980": [
      {
        postal_code: "1980",
        country_code: "BD",
        latitude: "24.28570000",
        longitude: "90.00030000",
        city: "Ghatial",
        state: "Dhaka Division",
        city_en: "Ghatial",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1981": [
      {
        postal_code: "1981",
        country_code: "BD",
        latitude: "24.28570000",
        longitude: "90.00030000",
        city: "Zahidganj",
        state: "Dhaka Division",
        city_en: "Zahidganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1982": [
      {
        postal_code: "1982",
        country_code: "BD",
        latitude: "24.28570000",
        longitude: "90.00030000",
        city: "D. Pakutia",
        state: "Dhaka Division",
        city_en: "D. Pakutia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1983": [
      {
        postal_code: "1983",
        country_code: "BD",
        latitude: "24.28570000",
        longitude: "90.00030000",
        city: "Dhalapara",
        state: "Dhaka Division",
        city_en: "Dhalapara",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1984": [
      {
        postal_code: "1984",
        country_code: "BD",
        latitude: "24.28570000",
        longitude: "90.00030000",
        city: "Lohani",
        state: "Dhaka Division",
        city_en: "Lohani",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1990": [
      {
        postal_code: "1990",
        country_code: "BD",
        latitude: "24.56010000",
        longitude: "89.92180000",
        city: "Gopalpur",
        state: "Dhaka Division",
        city_en: "Gopalpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1991": [
      {
        postal_code: "1991",
        country_code: "BD",
        latitude: "24.57930000",
        longitude: "89.93530000",
        city: "Jhowail",
        state: "Dhaka Division",
        city_en: "Jhowail",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1992": [
      {
        postal_code: "1992",
        country_code: "BD",
        latitude: "24.56580000",
        longitude: "89.85250000",
        city: "Hemnagar",
        state: "Dhaka Division",
        city_en: "Hemnagar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1996": [
      {
        postal_code: "1996",
        country_code: "BD",
        latitude: "24.61190000",
        longitude: "90.03150000",
        city: "Madhupur",
        state: "Dhaka Division",
        city_en: "Madhupur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "1997": [
      {
        postal_code: "1997",
        country_code: "BD",
        latitude: "24.57930000",
        longitude: "89.93530000",
        city: "Dhobari",
        state: "Dhaka Division",
        city_en: "Dhobari",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Tangail",
        province_code: "3093",
      },
    ],
    "2000": [
      {
        postal_code: "2000",
        country_code: "BD",
        latitude: "24.91970000",
        longitude: "89.94810000",
        city: "Jamalpur",
        state: "Dhaka Division",
        city_en: "Jamalpur",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2001": [
      {
        postal_code: "2001",
        country_code: "BD",
        latitude: "24.86720000",
        longitude: "90.03320000",
        city: "Nandina",
        state: "Dhaka Division",
        city_en: "Nandina",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "7700": [
      {
        postal_code: "7700",
        country_code: "BD",
        latitude: "23.71870000",
        longitude: "89.61050000",
        city: "Rajbari Sadar",
        state: "Dhaka Division",
        city_en: "Rajbari Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Rajbari",
        province_code: "3082",
      },
    ],
    "7710": [
      {
        postal_code: "7710",
        country_code: "BD",
        latitude: "23.72410000",
        longitude: "89.76500000",
        city: "Goalanda",
        state: "Dhaka Division",
        city_en: "Goalanda",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Rajbari",
        province_code: "3082",
      },
    ],
    "7711": [
      {
        postal_code: "7711",
        country_code: "BD",
        latitude: "23.69240000",
        longitude: "89.70640000",
        city: "Khankhanapur",
        state: "Dhaka Division",
        city_en: "Khankhanapur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Rajbari",
        province_code: "3082",
      },
    ],
    "7720": [
      {
        postal_code: "7720",
        country_code: "BD",
        latitude: "23.78080000",
        longitude: "89.42460000",
        city: "Pangsha",
        state: "Dhaka Division",
        city_en: "Pangsha",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Rajbari",
        province_code: "3082",
      },
    ],
    "7721": [
      {
        postal_code: "7721",
        country_code: "BD",
        latitude: "23.79680000",
        longitude: "89.35130000",
        city: "Ramkol",
        state: "Dhaka Division",
        city_en: "Ramkol",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Rajbari",
        province_code: "3082",
      },
    ],
    "7722": [
      {
        postal_code: "7722",
        country_code: "BD",
        latitude: "23.76480000",
        longitude: "89.49780000",
        city: "Ratandia",
        state: "Dhaka Division",
        city_en: "Ratandia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Rajbari",
        province_code: "3082",
      },
    ],
    "7723": [
      {
        postal_code: "7723",
        country_code: "BD",
        latitude: "23.78080000",
        longitude: "89.42460000",
        city: "Mrigibazar",
        state: "Dhaka Division",
        city_en: "Mrigibazar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Rajbari",
        province_code: "3082",
      },
    ],
    "7730": [
      {
        postal_code: "7730",
        country_code: "BD",
        latitude: "23.72520000",
        longitude: "89.72010000",
        city: "Baliakandi",
        state: "Dhaka Division",
        city_en: "Baliakandi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Rajbari",
        province_code: "3082",
      },
    ],
    "7731": [
      {
        postal_code: "7731",
        country_code: "BD",
        latitude: "23.60910000",
        longitude: "89.62260000",
        city: "Nalia",
        state: "Dhaka Division",
        city_en: "Nalia",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Rajbari",
        province_code: "3082",
      },
    ],
    "8000": [
      {
        postal_code: "8000",
        country_code: "BD",
        latitude: "23.25780000",
        longitude: "90.31520000",
        city: "Shariatpur Sadar",
        state: "Dhaka Division",
        city_en: "Shariatpur Sadar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8001": [
      {
        postal_code: "8001",
        country_code: "BD",
        latitude: "23.25780000",
        longitude: "90.31520000",
        city: "Angaria",
        state: "Dhaka Division",
        city_en: "Angaria",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8002": [
      {
        postal_code: "8002",
        country_code: "BD",
        latitude: "23.25780000",
        longitude: "90.31520000",
        city: "Chikandi",
        state: "Dhaka Division",
        city_en: "Chikandi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8010": [
      {
        postal_code: "8010",
        country_code: "BD",
        latitude: "23.23280000",
        longitude: "90.42420000",
        city: "Jajira",
        state: "Dhaka Division",
        city_en: "Jajira",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8020": [
      {
        postal_code: "8020",
        country_code: "BD",
        latitude: "23.30290000",
        longitude: "90.40870000",
        city: "Naria",
        state: "Dhaka Division",
        city_en: "Naria",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8021": [
      {
        postal_code: "8021",
        country_code: "BD",
        latitude: "23.27090000",
        longitude: "90.45300000",
        city: "Bhozeshwar",
        state: "Dhaka Division",
        city_en: "Bhozeshwar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8022": [
      {
        postal_code: "8022",
        country_code: "BD",
        latitude: "23.27070000",
        longitude: "90.47760000",
        city: "Gharisar",
        state: "Dhaka Division",
        city_en: "Gharisar",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8023": [
      {
        postal_code: "8023",
        country_code: "BD",
        latitude: "23.27090000",
        longitude: "90.45300000",
        city: "Upshi",
        state: "Dhaka Division",
        city_en: "Upshi",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8024": [
      {
        postal_code: "8024",
        country_code: "BD",
        latitude: "23.23910000",
        longitude: "90.47290000",
        city: "Kartikpur",
        state: "Dhaka Division",
        city_en: "Kartikpur",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8030": [
      {
        postal_code: "8030",
        country_code: "BD",
        latitude: "23.23280000",
        longitude: "90.42420000",
        city: "Bhedorganj",
        state: "Dhaka Division",
        city_en: "Bhedorganj",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8040": [
      {
        postal_code: "8040",
        country_code: "BD",
        latitude: "23.23280000",
        longitude: "90.42420000",
        city: "Damudhya",
        state: "Dhaka Division",
        city_en: "Damudhya",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
    "8050": [
      {
        postal_code: "8050",
        country_code: "BD",
        latitude: "23.09340000",
        longitude: "90.44680000",
        city: "Gosairhat",
        state: "Dhaka Division",
        city_en: "Gosairhat",
        state_en: "Dhaka Division",
        state_code: "81",
        province: "Shariatpur",
        province_code: "3086",
      },
    ],
  },
};

export default postOffices3;
