import { PostOfficeInfo } from "./IPostOfficeInfo";

const postOffices4: PostOfficeInfo = {
  query: {
    codes: [
      "2002",
      "2010",
      "2011",
      "2012",
      "2013",
      "2020",
      "2021",
      "2022",
      "2030",
      "2031",
      "2040",
      "2041",
      "2050",
      "2051",
      "2052",
      "2053",
      "2054",
      "2055",
      "2200",
      "2201",
      "2202",
      "2203",
      "2204",
      "2205",
      "2210",
      "2216",
      "2220",
      "2221",
      "2222",
      "2223",
      "2230",
      "2231",
      "2232",
      "2233",
      "2234",
      "2240",
      "2250",
      "2251",
      "2252",
      "2260",
      "2261",
      "2262",
      "2270",
      "2271",
      "2280",
      "2281",
      "2282",
      "2290",
      "2291",
      "2400",
      "2401",
      "2410",
      "2411",
      "2412",
      "2416",
      "2417",
      "2420",
      "2430",
      "2440",
      "2446",
      "2450",
      "2456",
      "2460",
      "2462",
      "2470",
      "2480",
      "2490",
      "2100",
      "2110",
      "2111",
      "2120",
      "2130",
      "2140",
      "2150",
      "2151",
    ],
    country: "bd",
  },
  results: {
    "2002": [
      {
        postal_code: "2002",
        country_code: "BD",
        latitude: "24.85290000",
        longitude: "90.13310000",
        city: "Narundi",
        state: "Dhaka Division",
        city_en: "Narundi",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2010": [
      {
        postal_code: "2010",
        country_code: "BD",
        latitude: "24.16140000",
        longitude: "89.99580000",
        city: "Malandah",
        state: "Dhaka Division",
        city_en: "Malandah",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2011": [
      {
        postal_code: "2011",
        country_code: "BD",
        latitude: "24.91970000",
        longitude: "89.94810000",
        city: "Jamalpur",
        state: "Dhaka Division",
        city_en: "Jamalpur",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2012": [
      {
        postal_code: "2012",
        country_code: "BD",
        latitude: "23.98330000",
        longitude: "90.20000000",
        city: "Malancha",
        state: "Dhaka Division",
        city_en: "Malancha",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2013": [
      {
        postal_code: "2013",
        country_code: "BD",
        latitude: "23.58120000",
        longitude: "89.83920000",
        city: "Mahmoodpur",
        state: "Dhaka Division",
        city_en: "Mahmoodpur",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2020": [
      {
        postal_code: "2020",
        country_code: "BD",
        latitude: "25.08080000",
        longitude: "89.79470000",
        city: "Islampur",
        state: "Dhaka Division",
        city_en: "Islampur",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2021": [
      {
        postal_code: "2021",
        country_code: "BD",
        latitude: "24.79130000",
        longitude: "89.92750000",
        city: "Durmoot",
        state: "Dhaka Division",
        city_en: "Durmoot",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2022": [
      {
        postal_code: "2022",
        country_code: "BD",
        latitude: "24.50170000",
        longitude: "90.06030000",
        city: "Gilabari",
        state: "Dhaka Division",
        city_en: "Gilabari",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2030": [
      {
        postal_code: "2030",
        country_code: "BD",
        latitude: "25.14240000",
        longitude: "89.76220000",
        city: "Dewangonj",
        state: "Dhaka Division",
        city_en: "Dewangonj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2031": [
      {
        postal_code: "2031",
        country_code: "BD",
        latitude: "25.14240000",
        longitude: "89.76220000",
        city: "Dewangonj S. Mills",
        state: "Dhaka Division",
        city_en: "Dewangonj S. Mills",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2040": [
      {
        postal_code: "2040",
        country_code: "BD",
        latitude: "24.66260000",
        longitude: "89.93780000",
        city: "Mathargonj",
        state: "Dhaka Division",
        city_en: "Mathargonj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2041": [
      {
        postal_code: "2041",
        country_code: "BD",
        latitude: "24.66260000",
        longitude: "89.93780000",
        city: "Balijhuri",
        state: "Dhaka Division",
        city_en: "Balijhuri",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2050": [
      {
        postal_code: "2050",
        country_code: "BD",
        latitude: "24.71990000",
        longitude: "89.79870000",
        city: "Shorishabari",
        state: "Dhaka Division",
        city_en: "Shorishabari",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2051": [
      {
        postal_code: "2051",
        country_code: "BD",
        latitude: "24.82470000",
        longitude: "89.78940000",
        city: "Gunerbari",
        state: "Dhaka Division",
        city_en: "Gunerbari",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2052": [
      {
        postal_code: "2052",
        country_code: "BD",
        latitude: "24.71990000",
        longitude: "89.79870000",
        city: "Bausee",
        state: "Dhaka Division",
        city_en: "Bausee",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2053": [
      {
        postal_code: "2053",
        country_code: "BD",
        latitude: "24.71990000",
        longitude: "89.79870000",
        city: "Jagannath Ghat",
        state: "Dhaka Division",
        city_en: "Jagannath Ghat",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2054": [
      {
        postal_code: "2054",
        country_code: "BD",
        latitude: "24.61510000",
        longitude: "89.80800000",
        city: "Pingna",
        state: "Dhaka Division",
        city_en: "Pingna",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2055": [
      {
        postal_code: "2055",
        country_code: "BD",
        latitude: "24.71990000",
        longitude: "89.79870000",
        city: "Jamuna Sar Karkhana",
        state: "Dhaka Division",
        city_en: "Jamuna Sar Karkhana",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Jamalpur",
        province_code: "3039",
      },
    ],
    "2100": [
      {
        postal_code: "2100",
        country_code: "BD",
        latitude: "25.09290000",
        longitude: "90.08270000",
        city: "Sherpur Shadar",
        state: "Dhaka Division",
        city_en: "Sherpur Shadar",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Sherpur",
        province_code: "3089",
      },
    ],
    "2110": [
      {
        postal_code: "2110",
        country_code: "BD",
        latitude: "25.08330000",
        longitude: "90.01950000",
        city: "Nalitabari",
        state: "Dhaka Division",
        city_en: "Nalitabari",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Sherpur",
        province_code: "3089",
      },
    ],
    "2111": [
      {
        postal_code: "2111",
        country_code: "BD",
        latitude: "25.13110000",
        longitude: "90.06660000",
        city: "Hatibandha",
        state: "Dhaka Division",
        city_en: "Hatibandha",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Sherpur",
        province_code: "3089",
      },
    ],
    "2120": [
      {
        postal_code: "2120",
        country_code: "BD",
        latitude: "25.18560000",
        longitude: "90.06680000",
        city: "Jhinaigati",
        state: "Dhaka Division",
        city_en: "Jhinaigati",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Sherpur",
        province_code: "3089",
      },
    ],
    "2130": [
      {
        postal_code: "2130",
        country_code: "BD",
        latitude: "25.09290000",
        longitude: "90.08270000",
        city: "Shribardi",
        state: "Dhaka Division",
        city_en: "Shribardi",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Sherpur",
        province_code: "3089",
      },
    ],
    "2140": [
      {
        postal_code: "2140",
        country_code: "BD",
        latitude: "25.09290000",
        longitude: "90.08270000",
        city: "Bakshigonj",
        state: "Dhaka Division",
        city_en: "Bakshigonj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Sherpur",
        province_code: "3089",
      },
    ],
    "2150": [
      {
        postal_code: "2150",
        country_code: "BD",
        latitude: "24.97140000",
        longitude: "90.17780000",
        city: "Nakla",
        state: "Dhaka Division",
        city_en: "Nakla",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Sherpur",
        province_code: "3089",
      },
    ],
    "2151": [
      {
        postal_code: "2151",
        country_code: "BD",
        latitude: "24.97140000",
        longitude: "90.17780000",
        city: "Gonopaddi",
        state: "Dhaka Division",
        city_en: "Gonopaddi",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Sherpur",
        province_code: "3089",
      },
    ],
    "2200": [
      {
        postal_code: "2200",
        country_code: "BD",
        latitude: "24.71920000",
        longitude: "90.65010000",
        city: "Mymensingh Sadar",
        state: "Dhaka Division",
        city_en: "Mymensingh Sadar",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2201": [
      {
        postal_code: "2201",
        country_code: "BD",
        latitude: "24.71920000",
        longitude: "90.65010000",
        city: "Kawatkhali",
        state: "Dhaka Division",
        city_en: "Kawatkhali",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2202": [
      {
        postal_code: "2202",
        country_code: "BD",
        latitude: "24.71920000",
        longitude: "90.65010000",
        city: "Agriculture Universi",
        state: "Dhaka Division",
        city_en: "Agriculture Universi",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2203": [
      {
        postal_code: "2203",
        country_code: "BD",
        latitude: "24.71920000",
        longitude: "90.65010000",
        city: "Shombhuganj",
        state: "Dhaka Division",
        city_en: "Shombhuganj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2204": [
      {
        postal_code: "2204",
        country_code: "BD",
        latitude: "24.71920000",
        longitude: "90.65010000",
        city: "Biddyaganj",
        state: "Dhaka Division",
        city_en: "Biddyaganj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2205": [
      {
        postal_code: "2205",
        country_code: "BD",
        latitude: "24.71920000",
        longitude: "90.65010000",
        city: "Pearpur",
        state: "Dhaka Division",
        city_en: "Pearpur",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2210": [
      {
        postal_code: "2210",
        country_code: "BD",
        latitude: "24.76480000",
        longitude: "90.25700000",
        city: "Muktagachha",
        state: "Dhaka Division",
        city_en: "Muktagachha",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2216": [
      {
        postal_code: "2216",
        country_code: "BD",
        latitude: "24.63230000",
        longitude: "90.26900000",
        city: "Fulbaria",
        state: "Dhaka Division",
        city_en: "Fulbaria",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2220": [
      {
        postal_code: "2220",
        country_code: "BD",
        latitude: "24.58170000",
        longitude: "90.39480000",
        city: "Trishal",
        state: "Dhaka Division",
        city_en: "Trishal",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2221": [
      {
        postal_code: "2221",
        country_code: "BD",
        latitude: "24.55710000",
        longitude: "90.44550000",
        city: "Ahmadbad",
        state: "Dhaka Division",
        city_en: "Ahmadbad",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2222": [
      {
        postal_code: "2222",
        country_code: "BD",
        latitude: "24.55710000",
        longitude: "90.44550000",
        city: "Ram Amritaganj",
        state: "Dhaka Division",
        city_en: "Ram Amritaganj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2223": [
      {
        postal_code: "2223",
        country_code: "BD",
        latitude: "24.53240000",
        longitude: "90.49610000",
        city: "Dhala",
        state: "Dhaka Division",
        city_en: "Dhala",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2230": [
      {
        postal_code: "2230",
        country_code: "BD",
        latitude: "24.37380000",
        longitude: "90.59180000",
        city: "Gaforgaon",
        state: "Dhaka Division",
        city_en: "Gaforgaon",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2231": [
      {
        postal_code: "2231",
        country_code: "BD",
        latitude: "24.37380000",
        longitude: "90.59180000",
        city: "Shibganj",
        state: "Dhaka Division",
        city_en: "Shibganj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2232": [
      {
        postal_code: "2232",
        country_code: "BD",
        latitude: "24.37380000",
        longitude: "90.59180000",
        city: "Usti",
        state: "Dhaka Division",
        city_en: "Usti",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2233": [
      {
        postal_code: "2233",
        country_code: "BD",
        latitude: "24.37380000",
        longitude: "90.59180000",
        city: "Kandipara",
        state: "Dhaka Division",
        city_en: "Kandipara",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2234": [
      {
        postal_code: "2234",
        country_code: "BD",
        latitude: "24.37380000",
        longitude: "90.59180000",
        city: "Duttarbazar",
        state: "Dhaka Division",
        city_en: "Duttarbazar",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2240": [
      {
        postal_code: "2240",
        country_code: "BD",
        latitude: "24.40480000",
        longitude: "90.38620000",
        city: "Bhaluka",
        state: "Dhaka Division",
        city_en: "Bhaluka",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2250": [
      {
        postal_code: "2250",
        country_code: "BD",
        latitude: "24.96080000",
        longitude: "90.45520000",
        city: "Phulpur",
        state: "Dhaka Division",
        city_en: "Phulpur",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2251": [
      {
        postal_code: "2251",
        country_code: "BD",
        latitude: "24.97780000",
        longitude: "90.44480000",
        city: "Beltia",
        state: "Dhaka Division",
        city_en: "Beltia",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2252": [
      {
        postal_code: "2252",
        country_code: "BD",
        latitude: "24.94390000",
        longitude: "90.46550000",
        city: "Tarakanda",
        state: "Dhaka Division",
        city_en: "Tarakanda",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2260": [
      {
        postal_code: "2260",
        country_code: "BD",
        latitude: "25.11710000",
        longitude: "90.33650000",
        city: "Haluaghat",
        state: "Dhaka Division",
        city_en: "Haluaghat",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2261": [
      {
        postal_code: "2261",
        country_code: "BD",
        latitude: "25.05810000",
        longitude: "90.33750000",
        city: "Dhara",
        state: "Dhaka Division",
        city_en: "Dhara",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2262": [
      {
        postal_code: "2262",
        country_code: "BD",
        latitude: "25.08760000",
        longitude: "90.33700000",
        city: "Munshirhat",
        state: "Dhaka Division",
        city_en: "Munshirhat",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2270": [
      {
        postal_code: "2270",
        country_code: "BD",
        latitude: "24.75970000",
        longitude: "90.56840000",
        city: "Gouripur",
        state: "Dhaka Division",
        city_en: "Gouripur",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2271": [
      {
        postal_code: "2271",
        country_code: "BD",
        latitude: "24.72030000",
        longitude: "90.55390000",
        city: "Ramgopalpur",
        state: "Dhaka Division",
        city_en: "Ramgopalpur",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2280": [
      {
        postal_code: "2280",
        country_code: "BD",
        latitude: "24.66290000",
        longitude: "90.69120000",
        city: "Isshwargonj",
        state: "Dhaka Division",
        city_en: "Isshwargonj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2281": [
      {
        postal_code: "2281",
        country_code: "BD",
        latitude: "24.69920000",
        longitude: "90.66580000",
        city: "Sohagi",
        state: "Dhaka Division",
        city_en: "Sohagi",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2282": [
      {
        postal_code: "2282",
        country_code: "BD",
        latitude: "24.62660000",
        longitude: "90.71660000",
        city: "Atharabari",
        state: "Dhaka Division",
        city_en: "Atharabari",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2290": [
      {
        postal_code: "2290",
        country_code: "BD",
        latitude: "24.56900000",
        longitude: "90.69010000",
        city: "Nandail",
        state: "Dhaka Division",
        city_en: "Nandail",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2291": [
      {
        postal_code: "2291",
        country_code: "BD",
        latitude: "24.58320000",
        longitude: "90.76090000",
        city: "Gangail",
        state: "Dhaka Division",
        city_en: "Gangail",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Mymensingh",
        province_code: "3061",
      },
    ],
    "2400": [
      {
        postal_code: "2400",
        country_code: "BD",
        latitude: "24.86440000",
        longitude: "90.83390000",
        city: "Netrakona Sadar",
        state: "Dhaka Division",
        city_en: "Netrakona Sadar",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2401": [
      {
        postal_code: "2401",
        country_code: "BD",
        latitude: "24.86440000",
        longitude: "90.83390000",
        city: "Baikherhati",
        state: "Dhaka Division",
        city_en: "Baikherhati",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2410": [
      {
        postal_code: "2410",
        country_code: "BD",
        latitude: "25.08670000",
        longitude: "90.51190000",
        city: "Purbadhola",
        state: "Dhaka Division",
        city_en: "Purbadhola",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2411": [
      {
        postal_code: "2411",
        country_code: "BD",
        latitude: "25.08670000",
        longitude: "90.51190000",
        city: "Shamgonj",
        state: "Dhaka Division",
        city_en: "Shamgonj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2412": [
      {
        postal_code: "2412",
        country_code: "BD",
        latitude: "25.08670000",
        longitude: "90.51190000",
        city: "Jaria Jhanjhail",
        state: "Dhaka Division",
        city_en: "Jaria Jhanjhail",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2416": [
      {
        postal_code: "2416",
        country_code: "BD",
        latitude: "25.08670000",
        longitude: "90.51190000",
        city: "Dhobaura",
        state: "Dhaka Division",
        city_en: "Dhobaura",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2417": [
      {
        postal_code: "2417",
        country_code: "BD",
        latitude: "25.08670000",
        longitude: "90.51190000",
        city: "Sakoai",
        state: "Dhaka Division",
        city_en: "Sakoai",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2420": [
      {
        postal_code: "2420",
        country_code: "BD",
        latitude: "24.86440000",
        longitude: "90.83390000",
        city: "Susnng Durgapur",
        state: "Dhaka Division",
        city_en: "Susnng Durgapur",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2430": [
      {
        postal_code: "2430",
        country_code: "BD",
        latitude: "25.00110000",
        longitude: "90.80770000",
        city: "Kalmakanda",
        state: "Dhaka Division",
        city_en: "Kalmakanda",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2440": [
      {
        postal_code: "2440",
        country_code: "BD",
        latitude: "24.89840000",
        longitude: "90.88650000",
        city: "Barhatta",
        state: "Dhaka Division",
        city_en: "Barhatta",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2446": [
      {
        postal_code: "2446",
        country_code: "BD",
        latitude: "24.87560000",
        longitude: "90.97770000",
        city: "Mohanganj",
        state: "Dhaka Division",
        city_en: "Mohanganj",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2450": [
      {
        postal_code: "2450",
        country_code: "BD",
        latitude: "24.86440000",
        longitude: "90.83390000",
        city: "Dharampasha",
        state: "Dhaka Division",
        city_en: "Dharampasha",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2456": [
      {
        postal_code: "2456",
        country_code: "BD",
        latitude: "24.86440000",
        longitude: "90.83390000",
        city: "Moddoynagar",
        state: "Dhaka Division",
        city_en: "Moddoynagar",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2460": [
      {
        postal_code: "2460",
        country_code: "BD",
        latitude: "24.86440000",
        longitude: "90.83390000",
        city: "Khaliajhri",
        state: "Dhaka Division",
        city_en: "Khaliajhri",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2462": [
      {
        postal_code: "2462",
        country_code: "BD",
        latitude: "24.86440000",
        longitude: "90.83390000",
        city: "Shaldigha",
        state: "Dhaka Division",
        city_en: "Shaldigha",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2470": [
      {
        postal_code: "2470",
        country_code: "BD",
        latitude: "24.81120000",
        longitude: "90.86160000",
        city: "Atpara",
        state: "Dhaka Division",
        city_en: "Atpara",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2480": [
      {
        postal_code: "2480",
        country_code: "BD",
        latitude: "24.66210000",
        longitude: "90.84300000",
        city: "Kendua",
        state: "Dhaka Division",
        city_en: "Kendua",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
    "2490": [
      {
        postal_code: "2490",
        country_code: "BD",
        latitude: "24.71580000",
        longitude: "90.94890000",
        city: "Madan",
        state: "Dhaka Division",
        city_en: "Madan",
        state_en: "Dhaka Division",
        state_code: "H",
        province: "Netrakona",
        province_code: "3072",
      },
    ],
  },
};

export default postOffices4;
